
<main>  
    <div class="circle circle1"></div>
    <div class="circle circle2"></div>
    <div class="circle circle3"></div>
    <div class="circle circle4"></div>
    
    <section class="conversations-container">
        <h1>Friends</h1>
        <?if(empty($friends)){?>
            <p>No friends found</p>    
        <?}?>
        <?foreach($friends as $friend){?>
            <div class="convos">
                <p><?=$friend->getUsername()?></p>
                <a href="do-add-friend.php?<?=$friend->getId()?>">Add</a>
            </div>
        <?}?> 
    </section>
</main>