<main>
    <h1 class="box-title">Sign in</h1>
    <div class="circle circle1"></div>
    <div class="circle circle2"></div>
    <div class="circle circle3"></div>
    <div class="circle circle4"></div>
    <form class="form-container" action="do-user-sign-in.php" method="POST">
        <?if(isset($_SERVER["QUERY_STRING"]) && $_SERVER["QUERY_STRING"]==="wrong_credentials"){?>
            <p class="error-message">wrong credentials</p>
        <?}?>
        <label for="usernmae">Username</label>
        <input class="text-input" type="text" name="username" value="" placeholder="Username">
        <label for="password">Password</label>
        <input class="text-input" type="password" name="password" value="" placeholder="Password">
        <input class="btn-input" type="submit" name="connect" value="Conncet">
        <a href="user-sign-up.php">Sign up</a>
    </form>
</div>